modLoader = "javafml"
loaderVersion = "[43,)"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/Faboslav/villages-and-pillages/issues"

[[mods]]
modId="${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.jpg"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villages-and-pillages"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "yungsapi"
mandatory = true
versionRange="[${minecraftVersion}-Forge-${yungsapiVersion},)"
ordering = "NONE"
side = "BOTH"
