modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/variants-and-ventures/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/variants-and-ventures"

[[mixins]]
config = "${modId}-common.mixins.json"

[[dependencies.${ modId }]]
modId = "minecraft"
required = true
versionRange = "[${minMinecraftVersion},)"

[[dependencies.${ modId }]]
modId = "yungsapi"
required = true
versionRange = "[${yungsapiMinecraftVersion}-NeoForge-${yungsapiVersion},)"
ordering = "NONE"
side = "BOTH"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"