name: "Build"

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.3.0
                with:
                    distribution: "temurin"
                    java-version: 17

            - name: "Initialize caches"
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            -   name: "Build with gradle"
                run: ./gradlew build