name: "Publish"

on:
    release:
        types: [ published ]

env:
    VERSION_TYPE: release
    JAVA_VERSIONS: |
        Java 17
        Java 18
    GAME_VERSIONS: |
        1.20.2
    FABRIC_DEPENDENCIES_CURSEFORGE: |
        fabric-api | depends | *
        yungs-api-fabric | depends | *
    FABRIC_DEPENDENCIES_MODRINTH: |
        fabric-api | depends | *
        yungs-api | depends | *
    FABRIC_LOADERS: |
        fabric
        quilt
    FORGE_LOADERS: |
        forge
        neoforge
    FORGE_DEPENDENCIES: |
        yungs-api | depends | *
    RETRY_ATTEMPTS: 3
    RELAY_DELAY: 10000
    VERSION_RESOLVER: latest

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3.5.3
                with:
                    fetch-depth: 0

            -   name: "Setup environment"
                uses: ./.github/actions/setup-environment

            -   name: "Build with gradle"
                run: ./gradlew build

            -   name: "Capture build artifacts"
                uses: actions/upload-artifact@v3
                with:
                    name: "villages-and-pillages"
                    path: |
                        fabric/build/libs/villagesandpillages-fabric-${{ github.ref_name }}.jar
                        forge/build/libs/villagesandpillages-forge-${{ github.ref_name }}.jar
                        LICENSE.txt

    publish-license-to-release:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish license to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish license to GitHub"
                uses: AButler/upload-release-assets@v2.0.2
                with:
                    files: 'LICENSE.txt'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Fabric to GitHub"
                uses: AButler/upload-release-assets@v2.0.2
                with:
                    files: fabric/build/libs/villagesandpillages-fabric-${{ github.ref_name }}.jar
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Fabric to CurseForge"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    curseforge-id: 915531
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: fabric/build/libs/villagesandpillages-fabric-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: ${{ env.FABRIC_LOADERS }}
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Villages&Pillages ${{ github.ref_name }} (Fabric/Quilt)
                    dependencies: ${{ env.FABRIC_DEPENDENCIES_CURSEFORGE }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-fabric-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Fabric to Modrinth"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    modrinth-id: klXONLDA
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: fabric/build/libs/villagesandpillages-fabric-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: ${{ env.FABRIC_LOADERS }}
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Villages&Pillages ${{ github.ref_name }} (Fabric/Quilt)
                    version: fabric-${{ github.ref_name }}
                    dependencies: ${{ env.FABRIC_DEPENDENCIES_MODRINTH }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-forge-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Forge to GitHub"
                uses: AButler/upload-release-assets@v2.0.2
                with:
                    files: forge/build/libs/villagesandpillages-forge-${{ github.ref_name }}.jar
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-forge-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Forge to CurseForge"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    curseforge-id: 915531
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: forge/build/libs/villagesandpillages-forge-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: ${{ env.FORGE_LOADERS }}
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Villages&Pillages ${{ github.ref_name }} (Forge/NeoForge)
                    dependencies: ${{ env.FORGE_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-forge-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3
                with:
                    name: "villages-and-pillages"

            -   name: "Publish Forge to Modrinth"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    modrinth-id: klXONLDA
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: forge/build/libs/villagesandpillages-forge-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: ${{ env.FORGE_LOADERS }}
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Villages&Pillages ${{ github.ref_name }} (Forge/NeoForge)
                    version: forge-${{ github.ref_name }}
                    dependencies: ${{ env.FORGE_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}